### ISSUE TITLE
无法加载插件

### ISSUE THREAD

**Issue by RandomEnch** [iyume/nonebot-plugin-arcaea#2]
使用python3.9.2以级nonebot2
加载插件时出现以下报错，请问如何解决？
03-21 14:11:28 [ERROR] nonebot | Failed to import "nonebot_plugin_arcaea"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\program files\python39\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "c:\program files\python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\program files\python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\uvicorn\subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\uvicorn\server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\program files\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\program files\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\program files\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\program files\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\uvicorn\server.py", line 56, in serve
    config.load()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\uvicorn\config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "c:\program files\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File ".\bot.py", line 24, in <module>
    nonebot.load_plugin('nonebot_plugin_arcaea')
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\nonebot\plugin\__init__.py", line 992, in load_plugin
    return context.run(_load_plugin, manager, module_path)
> File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\nonebot\plugin\__init__.py", line 960, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    return importlib.import_module(name)
  File "c:\program files\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\nonebot_plugin_arcaea\__init__.py", line 33, in <module>
    database = Database(f"sqlite:///{db_path}")
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\databases\core.py", line 66, in __init__
    backend_cls = import_from_string(backend_str)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\databases\importer.py", line 21, in import_from_string
    raise exc from None
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\databases\importer.py", line 18, in import_from_string
    module = importlib.import_module(module_str)
  File "c:\program files\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\databases\backends\sqlite.py", line 8, in <module>
    from sqlalchemy.engine.result import ResultMetaData, RowProxy
ImportError: cannot import name 'RowProxy' from 'sqlalchemy.engine.result' (C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\result.py)

**Comment by iyume** [comment]
说一下你使用的 nonebot2 的版本，包括 alpha 版本号

**Comment by RandomEnch** [comment]
最新版本v2.0.0a11

**Comment by iyume** [comment]
https://github.com/encode/databases/issues/298

看起来是由于 sqlalchemy 1.4.0 的更新移除了 `RowProxy`

**Comment by RandomEnch** [comment]
确实，换到sqlalchemy1.3.9版本之后成功加载了插件

**Comment by iyume** [comment]
重构后将不再依赖 `databases`, `aiosqlite`，届时将关闭此 issue
