### ISSUE TITLE
绑定code时出现如下报错

### ISSUE THREAD

**Issue by RandomEnch** [iyume/nonebot-plugin-arcaea#4]
06-30 03:06:05 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_arcaea.matcher, type=message, priority=1, temp=False>
06-30 03:06:05 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_arcaea.matcher, type=message, priority=1, temp=False> running complete
06-30 03:06:05 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_arcaea.matcher, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\nb_cli\commands\main.py", line 26, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\program files\python39\lib\site-packages\nonebot\__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "c:\program files\python39\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(app or self.server_app,
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\uvicorn\main.py", line 386, in run
    server.run()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\uvicorn\server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\program files\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\program files\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\program files\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\program files\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\program files\python39\lib\site-packages\nonebot\message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "c:\program files\python39\lib\site-packages\nonebot\message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
  File "c:\program files\python39\lib\site-packages\nonebot\matcher.py", line 544, in run
    await handler(self, bot, event, state_)
  File "c:\program files\python39\lib\site-packages\nonebot\handler.py", line 81, in __call__
    await self.func(
  File "src/plugins\nonebot_plugin_arcaea\handlers\bind.py", line 34, in bind_handler
    crud.user.create(cursor, qq, code=code)
  File "src/plugins\nonebot_plugin_arcaea\crud\crud_user.py", line 28, in create
    db.execute(
sqlite3.OperationalError: near "?": syntax error

**Comment by iyume** [comment]
此问题由此前的一个安全性更新产生。

出错变动位于 `git diff fd05 44f1 -- nonebot_plugin_arcaea/crud/crud_user.py`

已于 caf90c8667dd3178b6c8175575a6f8e60121fd0a 修复。

感谢反馈。

**Comment by iyume** [comment]
还有问题欢迎 reopen issue
