### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Adsicmes** [iyume/nonebot-plugin-arcaea#5]
![image](https://user-images.githubusercontent.com/79645438/127770766-50972e50-9da0-4bd7-9d00-3137da630d4f.png)
插件目录
![image](https://user-images.githubusercontent.com/79645438/127770776-6f555b6d-1056-44e8-bbf2-a8dcdf889926.png)
项目目录
![image](https://user-images.githubusercontent.com/79645438/127770788-29d46170-0e3f-42ff-bfff-0c95b9e174a0.png)
bot.py

从ERROR行开始的日志

08-01 12:21:14 [ERROR] nonebot | Failed to import "nonebot_plugin_arcaea"
Traceback (most recent call last):
  File "bot.py", line 23, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 1065, in load_from_toml
    return load_all_plugins(set(plugins), set(plugin_dirs))
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 1007, in load_all_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 154, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/__init__.py", line 1, in <module>
    from . import main
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/main.py", line 2, in <module>
    from . import handlers
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/handlers/__init__.py", line 1, in <module>
    from .info import info_handler
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/handlers/info.py", line 11, in <module>
    from ..api import ArcApiPlus
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/__init__.py", line 1, in <module>
    from .resolver import QueryResolver as ArcApiPlus
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/resolver.py", line 3, in <module>
    from ._base import APIQueryBase
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/_base.py", line 7, in <module>
    class APIQueryBase(abc.ABC):
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/_base.py", line 37, in APIQueryBase
    async def songalias(songid: str) -> list[str]:
TypeError: 'type' object is not subscriptable
08-01 12:21:14 [ERROR] nonebot | Failed to import "src/plugins/nonebot_plugin_arcaea"
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    nonebot.load_plugin("src/plugins/nonebot_plugin_arcaea")
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 960, in load_plugin
    return context.run(_load_plugin, manager, module_path)
> File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    return importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src/plugins/nonebot_plugin_arcaea'
08-01 12:21:14 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
08-01 12:21:14 [INFO] nonebot | Running NoneBot...
08-01 12:21:14 [DEBUG] nonebot | Loaded adapters: cqhttp

**Comment by iyume** [comment]
`load_plugin` 请使用包名导入。

示例 `nonebot.load_plugin('nonebot_plugin_arcaea')`

在你的情况应该是 `nonebot.load_plugin('src.plugins.nonebot_plugin_arcaea')`

**Comment by Adsicmes** [comment]
bot.py已经改了
现在是这样的
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import nonebot
from nonebot.adapters.cqhttp import Bot as CQHTTPBot

# Custom your logger
# 
# from nonebot.log import logger, default_format
# logger.add("error.log",
#            rotation="00:00",
#            diagnose=False,
#            level="ERROR",
#            format=default_format)

# You can pass some keyword args config to init function
nonebot.init()
app = nonebot.get_asgi()

driver = nonebot.get_driver()
driver.register_adapter("cqhttp", CQHTTPBot)

nonebot.load_from_toml("pyproject.toml")

nonebot.load_plugin("src.plugins.nonebot_plugin_arcaea")

# Modify some config / config depends on loaded configs
# 
# config = driver.config
# do something...


if __name__ == "__main__":
    nonebot.logger.warning("Always use `nb run` to start the bot instead of manually running!")
    nonebot.run(app="__mp_main__:app")
```

日志
```
adsicmes@adsicmes:~/QQbot/arc_bot/arcbot$ python3 bot.py 
08-01 12:32:31 [INFO] nonebot | NoneBot is initializing...
08-01 12:32:31 [INFO] nonebot | Current Env: dev
08-01 12:32:31 [DEBUG] nonebot | Loaded Config: {'driver': 'nonebot.drivers.fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'debug': True, 'api_root': {}, 'api_timeout': 30.0, 'access_token': None, 'secret': `None,` 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev'}
08-01 12:32:31 [DEBUG] nonebot | Succeeded to load adapter "cqhttp"
08-01 12:32:31 [ERROR] nonebot | Failed to import "nonebot_plugin_arcaea"
Traceback (most recent call last):
  File "bot.py", line 23, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 1065, in load_from_toml
    return load_all_plugins(set(plugins), set(plugin_dirs))
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 1007, in load_all_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 154, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/__init__.py", line 1, in <module>
    from . import main
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/main.py", line 2, in <module>
    from . import handlers
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/handlers/__init__.py", line 1, in <module>
    from .info import info_handler
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/handlers/info.py", line 11, in <module>
    from ..api import ArcApiPlus
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/__init__.py", line 1, in <module>
    from .resolver import QueryResolver as ArcApiPlus
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/resolver.py", line 3, in <module>
    from ._base import APIQueryBase
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/_base.py", line 7, in <module>
    class APIQueryBase(abc.ABC):
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/_base.py", line 37, in APIQueryBase
    async def songalias(songid: str) -> list[str]:
TypeError: 'type' object is not subscriptable
08-01 12:32:31 [ERROR] nonebot | Failed to import "src/plugins/nonebot_plugin_arcaea"
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    nonebot.load_plugin("src/plugins/nonebot_plugin_arcaea")
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 960, in load_plugin
    return context.run(_load_plugin, manager, module_path)
> File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    return importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src/plugins/nonebot_plugin_arcaea'
08-01 12:32:31 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
08-01 12:32:31 [INFO] nonebot | Running NoneBot...
08-01 12:32:31 [DEBUG] nonebot | Loaded adapters: cqhttp
08-01 12:32:31 [ERROR] uvicorn | [Errno 98] Address already in use
adsicmes@adsicmes:~/QQbot/arc_bot/arcbot$ ls 
bot.py  docker-compose.yml  Dockerfile  pyproject.toml  README.md  src
adsicmes@adsicmes:~/QQbot/arc_bot/arcbot$ nano .env
adsicmes@adsicmes:~/QQbot/arc_bot/arcbot$ nano bot.py 
adsicmes@adsicmes:~/QQbot/arc_bot/arcbot$ python3 bot.py 
08-01 12:34:49 [INFO] nonebot | NoneBot is initializing...
08-01 12:34:49 [INFO] nonebot | Current Env: dev
08-01 12:34:49 [DEBUG] nonebot | Loaded Config: {'driver': 'nonebot.drivers.fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'debug': True, 'api_root': {}, 'api_timeout': 30.0, 'access_token': None, 'secret': None, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev'}
08-01 12:34:49 [DEBUG] nonebot | Succeeded to load adapter "cqhttp"
08-01 12:34:50 [ERROR] nonebot | Failed to import "nonebot_plugin_arcaea"
Traceback (most recent call last):
  File "bot.py", line 23, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 1065, in load_from_toml
    return load_all_plugins(set(plugins), set(plugin_dirs))
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 1007, in load_all_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 154, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/__init__.py", line 1, in <module>
    from . import main
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/main.py", line 2, in <module>
    from . import handlers
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/handlers/__init__.py", line 1, in <module>
    from .info import info_handler
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/handlers/info.py", line 11, in <module>
    from ..api import ArcApiPlus
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/__init__.py", line 1, in <module>
    from .resolver import QueryResolver as ArcApiPlus
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/resolver.py", line 3, in <module>
    from ._base import APIQueryBase
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/_base.py", line 7, in <module>
    class APIQueryBase(abc.ABC):
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/_base.py", line 37, in APIQueryBase
    async def songalias(songid: str) -> list[str]:
TypeError: 'type' object is not subscriptable
08-01 12:34:50 [WARNING] nonebot | Duplicated prefix rule "/a "
08-01 12:34:50 [WARNING] nonebot | Duplicated prefix rule "/arc"
08-01 12:34:50 [ERROR] nonebot | Failed to import "src.plugins.nonebot_plugin_arcaea"
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    nonebot.load_plugin("src.plugins.nonebot_plugin_arcaea")
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 960, in load_plugin
    return context.run(_load_plugin, manager, module_path)
> File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    return importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/adsicmes/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/__init__.py", line 1, in <module>
    from . import main
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/main.py", line 2, in <module>
    from . import handlers
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/handlers/__init__.py", line 1, in <module>
    from .info import info_handler
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/handlers/info.py", line 11, in <module>
    from ..api import ArcApiPlus
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/__init__.py", line 1, in <module>
    from .resolver import QueryResolver as ArcApiPlus
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/resolver.py", line 3, in <module>
    from ._base import APIQueryBase
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/_base.py", line 7, in <module>
    class APIQueryBase(abc.ABC):
  File "/home/adsicmes/QQbot/arc_bot/arcbot/src/plugins/nonebot_plugin_arcaea/api/_base.py", line 37, in APIQueryBase
    async def songalias(songid: str) -> list[str]:
TypeError: 'type' object is not subscriptable
08-01 12:34:50 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
08-01 12:34:50 [INFO] nonebot | Running NoneBot...
08-01 12:34:50 [DEBUG] nonebot | Loaded adapters: cqhttp
08-01 12:34:50 [ERROR] uvicorn | [Errno 98] Address already in use
adsicmes@adsicmes:~/QQbot/arc_bot/arcbot$ 

```

**Comment by iyume** [comment]
应该是 python 版本太低，不支持 primitive data type subscription

**Comment by iyume** [comment]
应该算是一个 bug，感谢 report

已于 cd2110b11ae41707396a0db21f228474cc3e35b4 修复

请拉取最新版本的源码

**Comment by Adsicmes** [comment]
感谢

**Comment by iyume** [comment]
建议不要使用 `load_plugin` 导入本地目录，没有命名空间，会导致 logger 错误

将插件置于目录内并使用 `load_plugins` 是对于本地插件较好的管理方式

**Comment by Adsicmes** [comment]
感谢

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/127771870-3cea0af1-5e3d-48d3-84b7-4ad7de4c7a19.png)
这样？

**Comment by iyume** [comment]
是的
